// eslint-disable-next-line
export default {
  EMAILJS_PUBLIC_KEYS: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEYS,
  EMAILJS_PRIVATE_KEYS: process.env.NEXT_PUBLIC_EMAILJS_PRIVATE_KEYS,
  EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: process.env.NEXT_PUBLIC_TEMPLATE_ID,
};
